- hosts: monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    vagrant
  roles:
   - monitoring
   - grafana

  environment:
     http_proxy: http://rodionovm.ru:8118
     https_proxy: http://rodionovm.ru:8118
