- hosts: nginx
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    vagrant
  roles:
   - install_nginx_letsencrypt
   - install_proxy
   - install_node_exporter
